travis:
  secure:
    BINSTAR_TOKEN: Xj7I/gsunvnUJjWgP0WcB2P5j4Bqt7zootkiNoxV+Dx3mZBm4n3Wh9Xb4iny9hFwkPJ0bSe5Esm4s21q2fXO7bJ5GFv0QlP0RyZ8XyIGswIgK9skubiXYM41/65O/7VcPTy9xer79oaBwMFMP+/HD8R4Q+8Ixd7++t+ZwHAQqE0AOYwTko0N44A7WF3+q/18mBxhoAEQY+uorEH7yfZdZAiGtGHKkjj7pY+0uO+ug8luKW98lVRwVk9VHaQK8eZk6G/6H1pqhxF365/hGevCkejQCSwX9uYGmsUoTp3l1mMcK3tn2T/Jq4dEoVWV3Vjg5HGQq4s5h5PUJwbk/EBRqPcUkVrUj1+EBhKPjfXmA/mubOCHJFX10fmEvSQkhsg1Oh3xAQVRvccmfghofk0Z2Hr61wwv55/XOAX7stXI0F0qSkiakU+mbCJTgDbM7iZh0eEej3n/TlKLwpYuQIIEsvcWjFjhCF22gnQpgfxxN6RNlnxmhTjkXK12J6Mw4s/iGmXHqwzNNe3BD9izZSmo/L5cpUViou+nNjfdRMOx8/gp2FUD57pPL61pV+CigiQ8dxq9GoAZgAi1At9QzOAvzDYhyU98ke3bgcbJAQiYG19dZZaqrEbEeHy2DGQnLXZYU7VAtLOa9hrKJu2V2VEMc24P2tT74rXw5q2+2YDMrRg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
